apiVersion: apps/v1

kind: Deployment

metadata:
  name: newuserdb-deployment

  labels:
    app: node-16

spec:
  replicas: 2

  selector:
    matchLabels:
      app: node-16

  template:
    metadata:
      labels:
        app: node-16

    spec:
      containers:
        - name: node

          image: kaviuln/image_7.1:2

          ports:
            - containerPort: 1334
